name = "nuxt-lazy-loading-workers-test"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2022-09-10"
rules = [
  { type = "ESModule", globs = ["**/*.js", "**/*.mjs"]},
]

[site]
  bucket = ".output/public"